sudo: required
language: php
os: trusty
php:
  - 7.1
  
#branche yg digunakan
branches:
  only:
    - master #-> QA/Staging server
    - master #-> DevServer

# install Environment di OS
before_script:
  - cp .env.travis .env
  - composer install --no-interaction
  - php artisan key:genarate

# Main Exception (Build)
script:
  - ./vendor/bin/phpunit

  after_success: