sudo: required
language: php
php:
  - 7.1
  
#branche yg digunakan
branches:
  only:
    - master #-> QA/Staging server
    - master #-> DevServer

# install Environment di OS
before_install
  - curl -LO https://storage.googleapis.com/kubernet-release/release/$(curl -s https://storage.googleapis.com/kubernet-release/stable.txt) /bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - sudo mv ./kubectl /usr/localbin/kubenctl
# Precompile
before_script:

# Main Exception (Build)
script: